name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      # Install dependencies (if applicable)
      - name: Install dependencies
        run: |
          npm install  # Replace with your package manager if not using Node.js

      # Build the project (if applicable)
      - name: Build project
        run: |
          npm run build  # Replace with your build command

      # Deploy to AWS (e.g., S3, ECS, Lambda, etc.)
      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://your-bucket-name --delete
