name: PR Test Cases

on:
  pull_request:
    branches:
      - main # Run tests on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install  # Replace with your package manager if not using Node.js

      # Run tests
      - name: Run tests
        run: |
          npm test  # Replace with your test command
